[package]
name = "dbus"
version = "1.16.2"
summary = "Message bus system"
license = "AFL-2.1 OR GPL-2.0-or-later"
homepage = "https://www.freedesktop.org/wiki/Software/dbus/"

[[source]]
sha256 = "0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"
urls = ["https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz",
        "https://archive.ubuntu.com/ubuntu/pool/main/d/dbus/dbus_1.16.2.orig.tar.xz"]
file = "dbus_1.16.2.orig.tar.xz"

[build]
script = '''
mkdir build && cd build
meson setup --prefix=/usr --buildtype=release --wrap-mode=nofallback \
  -D doxygen_docs=disabled -D xml_docs=disabled -D systemd=enabled ..
ninja
DESTDIR="$DESTDIR" ninja install
mkdir -p "$DESTDIR/var/lib/dbus"
ln -sf /etc/machine-id "$DESTDIR/var/lib/dbus/machine-id"
'''

[ai]
kind = "service"
keywords = ["dbus", "message bus"]
