[package]
name = "file"
version = "5.46"
summary = "File type identification (file, libmagic)"
license = "BSD-2-Clause"
homepage = "https://www.darwinsys.com/file/"

[[source]]
sha256 = "c9cc77c7c560c543135edc555af609d5619dbef011997e988ce40a3d75d86088"
urls = ["https://astron.com/pub/file/file-5.46.tar.gz",
        "https://archive.ubuntu.com/ubuntu/pool/main/f/file/file_5.46.orig.tar.gz"]
file = "file_5.46.orig.tar.gz"

[build]
script = '''
./configure --prefix=/usr 
make
make DESTDIR="$DESTDIR" install
'''

[ai]
kind = "cli"
launch = "file"
keywords = ["file type", "identify file"]
