[package]
name = "libseccomp"
version = "2.6.0"
summary = "System call filtering library"
license = "LGPL-2.1-only"
homepage = "https://github.com/seccomp/libseccomp"

[[source]]
sha256 = "83b6085232d1588c379dc9b9cae47bb37407cf262e6e74993c61ba72d2a784dc"
urls = ["https://github.com/seccomp/libseccomp/releases/download/v2.6.0/libseccomp-2.6.0.tar.gz",
        "https://archive.ubuntu.com/ubuntu/pool/main/libs/libseccomp/libseccomp_2.6.0.orig.tar.gz"]
file = "libseccomp_2.6.0.orig.tar.gz"

[build]
script = '''
./configure --prefix=/usr --disable-static
make
make DESTDIR="$DESTDIR" install
'''
