[package]
name = "ninja"
version = "1.13.2"
summary = "Small build system"
license = "Apache-2.0"
homepage = "https://ninja-build.org/"

[[source]]
sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17"
urls = ["https://archive.ubuntu.com/ubuntu/pool/universe/n/ninja-build/ninja-build_1.13.2.orig.tar.gz"]

[build]
script = '''
python3 configure.py --bootstrap --verbose
install -Dm755 ninja "$DESTDIR/usr/bin/ninja"
'''
