[package]
name = "perl"
version = "5.40.1"
summary = "Perl 5 interpreter"
license = "Artistic-1.0-Perl OR GPL-1.0-or-later"
homepage = "https://www.perl.org/"

[[source]]
sha256 = "dfa20c2eef2b4af133525610bbb65dd13777ecf998c9c5b1ccf0d308e732ee3f"
urls = ["https://www.cpan.org/src/5.0/perl-5.40.1.tar.xz",
        "https://archive.ubuntu.com/ubuntu/pool/main/p/perl/perl_5.40.1.orig.tar.xz"]
file = "perl_5.40.1.orig.tar.xz"

[build]
script = '''
export BUILD_ZLIB=False BUILD_BZIP2=0
sh Configure -des -D prefix=/usr -D vendorprefix=/usr \
  -D privlib=/usr/lib/perl5/5.40/core_perl -D archlib=/usr/lib/perl5/5.40/core_perl \
  -D sitelib=/usr/lib/perl5/5.40/site_perl -D sitearch=/usr/lib/perl5/5.40/site_perl \
  -D vendorlib=/usr/lib/perl5/5.40/vendor_perl -D vendorarch=/usr/lib/perl5/5.40/vendor_perl \
  -D man1dir=/usr/share/man/man1 -D man3dir=/usr/share/man/man3 \
  -D pager="/usr/bin/less -isR" -D useshrplib -D usethreads
make
make DESTDIR="$DESTDIR" install
'''

[ai]
kind = "tui"
launch = "less"
keywords = ["pager", "view file"]

