[package]
name = "perl-xml-parser"
version = "2.47"
summary = "Perl interface to expat"
license = "Artistic-1.0-Perl OR GPL-1.0-or-later"
homepage = "https://github.com/cpan-authors/XML-Parser"

[[source]]
sha256 = "ad4aae643ec784f489b956abe952432871a622d4e2b5c619e8855accbfc4d1d8"
urls = ["https://archive.ubuntu.com/ubuntu/pool/main/libx/libxml-parser-perl/libxml-parser-perl_2.47.orig.tar.gz"]

[build]
script = '''
perl Makefile.PL
make
make DESTDIR="$DESTDIR" install
find "$DESTDIR" -name perllocal.pod -delete
'''
